image: Visual Studio 2019

environment:
  matrix:
    - USE_MSVC: 1
      QTDIR: C:\Qt\5.15\msvc2019
      QTTOOLS: C:\Qt\Tools\QtCreator
    - USE_MINGW: 1
      QTDIR: C:\Qt\5.15\mingw81_32
      QTTOOLS: C:\Qt\Tools\mingw810_32

install:
  - DIR C:\Qt
  - DIR C:\Qt\Tools
  - DIR %QTDIR%\..
  - DIR %QTTOOLS%
  - set PATH=%QTDIR%\bin;%QTTOOLS%\bin;%PATH%
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"'

before_build:
  - qmake -config release Makou_Reactor.pro

build_script:
  - if "%USE_MSVC%"=="1" nmake
  - if "%USE_MINGW%"=="1" mingw32-make

after_build:
  - FOR /F %%i IN ('git describe --tags') DO SET GIT_TAG_OR_BRANCH=%%i
  - if "%USE_MSVC%"=="1" set DEPLOY_DIR="makoureactor-%GIT_TAG_OR_BRANCH%-win32"
  - if "%USE_MINGW%"=="1" set DEPLOY_DIR="makoureactor-%GIT_TAG_OR_BRANCH%-win32-xp"
  - echo "%DEPLOY_DIR%"
  - deploy.bat
  - MOVE *.qm deploy
  - DIR deploy
  - MOVE deploy "%DEPLOY_DIR%"
  - 7z a "%DEPLOY_DIR%.zip" "%DEPLOY_DIR%"

artifacts:
  - path: makoureactor-*.zip

deploy:
  description: Description # Mandatory
  provider: GitHub
  auth_token:
    secure: FFSAXpL8H1r+SbvKgFx9JgXEYOI3BS7KcyJGK384TJVb+78rGQ8MAmSBEKTyzqm7
  artifact: /makoureactor-.*\.zip/
  on:
    branch: develop
    appveyor_repo_tag: true # deploy on tag push only
